name: ux
description: UX Kit
version: 0.2.0
homepage: https://swipelab.co/ux.html

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.swipelab.ux
    pluginClass: UxPlugin