name: ux
description: UX Kit
version: 0.1.1
author: Alexandru Agrapine <alex@swipelab.co>
homepage: https://swipelab.co/ux.html

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.swipelab.ux
    pluginClass: UxPlugin