name: ux
description: UX Kit
version: 0.0.2
author: Alexandru R. Agrapine <alex@swipelab.co>
homepage: https://swipelab.co/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.swipelab.ux
    pluginClass: UxPlugin